### ISSUE TITLE
Jio TV service upload on server

### ISSUE THREAD

**Issue by rds8896** [stephenvaz03/C-137#1]
Hey, Can you help me in understanding how to upload standalone botallen proxy on a server to use it on firestick?

**Comment by stephenvaz** [comment]
you'd need to run the proxy(bin file) on a server, for example you can use linode(https://www.linode.com/products/shared/) you'll get your own terminal, wherein you can run the proxy for 24x7. Usually these services are paid and the free ones will have some kind of trial, so the best thing would be to run the proxy locally, maybe even on the firestick(using termux) or some other android device. For futher help you may contact me at stephenvaz03@outlook.com
